import rpgbot
import requests
import json


def main():
    bot = rpgbot.RPGBot()
    bot.run()


''' Sends a get request to the given url, returns the Response object
    generated by the get request and decoded from utf8
'''


def get_url(url):
    response = requests.get(url)
    content = response.content.decode("utf8")
    return content


''' Parses the JSON content from the request into a JSON object '''


def get_json_from_url(url):
    content = get_url(url)
    js = json.loads(content)
    return js


if __name__ == '__main__':
    main()
